# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "09db052843481c0fb9b9be386a2309a4"
name = "practice-app"
application_url = "https://1f94-2600-1700-8461-a830-8a1a-86f8-aa6b-e67f.ngrok-free.app/"
embedded = true

[build]
dev_store_url = "saular-test-app.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://1f94-2600-1700-8461-a830-8a1a-86f8-aa6b-e67f.ngrok-free.app/apps/default-app-home/api/auth"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
