# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "09db052843481c0fb9b9be386a2309a4"
name = "practice-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "saular-test-app.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
